spec:
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "false"   
        metadata.dynatrace.com/process.technology: "go"         
    spec:
      containers:
        - name: productcatalogservice
          image: ghcr.io/open-telemetry/demo:1.12.0-productcatalogservice
          imagePullPolicy: Always
          env:
            - name: OTEL_COLLECTOR_NAME
              value: 'dynatrace-otel-gateway-collector'
            - name: OTEL_GO_AUTO_INSTRUMENTATION_ENABLED # Not currently supported - https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/241
              value: 'false'
          volumeMounts:
            - mountPath: "/usr/src/app/products/"
              name: volume
              readOnly: false
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: product-catalog-storage