spec:
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "false"   
        metadata.dynatrace.com/process.technology: "PHP"        
    spec:
      containers:
        - name: quoteservice
          image: ghcr.io/open-telemetry/demo:1.12.0-quoteservice
          imagePullPolicy: Always
          env:
            - name: OTEL_COLLECTOR_NAME
              value: 'dynatrace-otel-gateway-collector'
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: 'true'
            - name: OTEL_PHP_DISABLED_INSTRUMENTATIONS
              value: '' # Disable 'all','slim,psr15,psr18' instrumentations  