apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-catalog-storage
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/products"