apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-catalog-storage
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi